<?php

return [
    "max_compteur_ref_id_natio_sportif" => env('MAX_COMPTEUR_REF_ID_NATIO_SPORTIF'),
    "min_compteur_ref_id_natio_sportif" => env('MIN_COMPTEUR_REF_ID_NATIO_SPORTIF'),
    "min_2_lettres" => env('MIN_2_LETTRES'),
    "max_2_lettres" => env('MAX_2_LETTRES'),
    "lettres" => [
        "A" => array('next' => 'B', 'previous' => 'Z'),
        "B" => array('next' => 'C', 'previous' => 'A'),
        "C" => array('next' => 'D', 'previous' => 'B'),
        "D" => array('next' => 'E', 'previous' => 'C'),
        "E" => array('next' => 'F', 'previous' => 'D'),
        "F" => array('next' => 'G', 'previous' => 'E'),
        "G" => array('next' => 'H', 'previous' => 'F'),
        "H" => array('next' => 'I', 'previous' => 'G'),
        "I" => array('next' => 'J', 'previous' => 'H'),
        "J" => array('next' => 'K', 'previous' => 'I'),
        "K" => array('next' => 'L', 'previous' => 'J'),
        "L" => array('next' => 'M', 'previous' => 'K'),
        "M" => array('next' => 'N', 'previous' => 'L'),
        "N" => array('next' => 'P', 'previous' => 'M'),
        //"O" => array('next' => 'P', 'previous' => 'A'),
        "P" => array('next' => 'Q', 'previous' => 'N'),
        "Q" => array('next' => 'R', 'previous' => 'P'),
        "R" => array('next' => 'S', 'previous' => 'Q'),
        "S" => array('next' => 'T', 'previous' => 'R'),
        "T" => array('next' => 'U', 'previous' => 'S'),
        "U" => array('next' => 'V', 'previous' => 'T'),
        "V" => array('next' => 'W', 'previous' => 'U'),
        "W" => array('next' => 'X', 'previous' => 'V'),
        "X" => array('next' => 'Y', 'previous' => 'W'),
        "Y" => array('next' => 'Z', 'previous' => 'X'),
        "Z" => array('next' => 'A', 'previous' => 'Y'),
    ],
    //"A" => array('current' => 'A', 'next' => 'B', 'previous' => ''),
];
